CREATE TABLE IF NOT EXISTS users (
    acct VARCHAR(255) PRIMARY KEY NOT NULL,
    pwd VARCHAR(255) NOT NULL,
    fullname VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);
